/* LAS ESPECIES DE BORNEO (Maliau y Sabah) que se dibujan, cada una con el grupo del motor
   (Virtual Ecosystem) al que pertenece y de dónde sale el dato. Lo de «donde» viene de las
   observaciones de iNaturalist en la cuenca de Maliau (place 193460) y en Sabah (13134),
   descargadas el 3-oct-2026 en .teams/datos/fauna/. «encaje» dice si el animal real cuadra
   con el grupo del motor (bueno), solo en parte (aprox) o si no hay ninguno real y es un
   sustituto para poder dibujar el grupo (sustituto). */

export const GRUPOS = {
  carnivorous_mammal: 'Mamífero carnívoro (40 kg)',
  herbivorous_mammal: 'Mamífero herbívoro (10 kg)',
  fungivorous_mammal: 'Mamífero fungívoro (10 kg)',
  scavenging_mammal: 'Mamífero carroñero (20 kg)',
  carnivorous_bird: 'Ave carnívora (1 kg)',
  herbivorous_bird: 'Ave herbívora (0,5 kg)',
  swallow: 'Golondrina (0,2 kg)',
  frog: 'Rana (0,5 kg)',
  herbivorous_lizard: 'Lagarto herbívoro (0,5 kg)',
  thermophilic_lizard: 'Lagarto termófilo (0,3 kg)',
  carnivorous_snake: 'Serpiente carnívora (1 kg)',
  carnivorous_insect_iteroparous: 'Insecto carnívoro, cría muchas veces',
  carnivorous_insect_semelparous: 'Insecto carnívoro, cría una vez',
  herbivorous_insect_iteroparous: 'Insecto herbívoro, cría muchas veces',
  herbivorous_insect_semelparous: 'Insecto herbívoro, cría una vez',
  caterpillar: 'Oruga',
  butterfly: 'Mariposa',
  earthworm: 'Lombriz',
  dung_beetle: 'Escarabajo pelotero',
  detritivorous_insect: 'Insecto de hojarasca',
};

const INAT = 'https://www.inaturalist.org/places/193460';

export const ANIMALES = [
  // ---- mamíferos
  { id: 'pantera-nebulosa', nombre: 'Pantera nebulosa de la Sonda', cientifico: 'Neofelis diardi', cat: 'Mamíferos', grupo: 'carnivorous_mammal',
    dieta: 'Ciervos, jabalíes, monos, puercoespines', peso: '12–26 kg', donde: 'Maliau y Sabah', encaje: 'bueno',
    nota: 'El mayor felino de Borneo. Pesa la mitad que el grupo del motor.', fuente: 'https://en.wikipedia.org/wiki/Sunda_clouded_leopard',
    modelo: { rig: 'cuadrupedo', largo: 1.3, alto: 0.55, ancho: 0.36, patasRel: 0.4, pataGruesa: 1.3, zarpaGrande: true, pelo: '#8a8064', barriga: '#cac0a6', patas: '#7a7058', manchas: { color: '#1e1a14', n: 16, tam: 0.34, borde: '#5e553e' }, nuca: { n: 2, color: '#16120e', grueso: 1.6 }, cola: 'larga', colaLargo: 1.15, colaGruesa: 0.26, orejas: 'redondas', orejaColor: '#6a6250', hocico: 0.14, felino: true, iris: '#b8a050' } },
  { id: 'gato-leopardo', nombre: 'Gato leopardo de la Sonda', cientifico: 'Prionailurus javanensis', cat: 'Mamíferos', grupo: 'carnivorous_mammal',
    dieta: 'Roedores, aves, ranas, insectos', peso: '0,5–4 kg', donde: 'Sabah', encaje: 'aprox',
    nota: 'Variante pequeña del mismo grupo: se usaría para cohortes de poco peso.', fuente: 'https://www.inaturalist.org/taxa/922736',
    modelo: { rig: 'cuadrupedo', largo: 0.5, alto: 0.36, ancho: 0.15, patasRel: 0.54, pataGruesa: 0.85, cabezaRel: 1.2, ojoGrande: true, pelo: '#c2a070', barriga: '#f0e8d6', patas: '#cdb48c', manchas: { color: '#141010', n: 26, tam: 0.16 }, nuca: { n: 4, color: '#141010' }, cola: 'larga', colaLargo: 0.26, colaGruesa: 0.16, anillos: '#141010', puntaCola: '#141010', orejas: 'redondas', orejaGrande: 1.2, orejaColor: '#141010', orejaMancha: '#f4efe2', caraBlanca: '#f6f0e4', hocico: 0.04, felino: true, iris: '#d8b04a' } },
  { id: 'muntiaco', nombre: 'Muntíaco amarillo de Borneo', cientifico: 'Muntiacus atherodes', cat: 'Mamíferos', grupo: 'herbivorous_mammal',
    dieta: 'Hojas, fruta caída, brotes, semillas', peso: '13–18 kg', donde: 'Maliau (ciervo ladrador) y Sabah', encaje: 'bueno',
    nota: '', fuente: 'https://animaldiversity.org/accounts/Muntiacus_atherodes/',
    modelo: { rig: 'cuadrupedo', largo: 0.85, alto: 0.68, ancho: 0.26, pelo: '#c8893a', barriga: '#f0e2c4', lomo: '#9a6224', patas: '#7a4e22', cola: 'corta', orejas: 'ciervo', cuernos: 'muntiaco', hocico: 0.14, patasFinas: true } },
  { id: 'ciervo-raton', nombre: 'Ciervo ratón mayor', cientifico: 'Tragulus napu', cat: 'Mamíferos', grupo: 'herbivorous_mammal',
    dieta: 'Hojas, brotes, fruta caída', peso: '5–8 kg', donde: 'Maliau', encaje: 'aprox',
    nota: 'Variante pequeña del grupo herbívoro.', fuente: 'https://www.inaturalist.org/taxa/42109',
    modelo: { rig: 'cuadrupedo', largo: 0.5, alto: 0.34, ancho: 0.17, pelo: '#7a5e44', barriga: '#efe6d4', patas: '#5a4232', rayasGarganta: '#f4efe4', encorvado: true, cola: 'corta', orejas: 'ciervo', hocico: 0.08, patasFinas: true } },
  { id: 'orangutan', nombre: 'Orangután de Borneo', cientifico: 'Pongo pygmaeus', cat: 'Mamíferos', grupo: 'herbivorous_mammal',
    dieta: 'Sobre todo fruta (higos), hojas, corteza', peso: '30–90 kg', donde: 'Sabah', encaje: 'aprox',
    nota: 'Frugívoro grande: el motor no tiene grupo de primates, cae en herbívoro.', fuente: 'https://www.inaturalist.org/taxa/43582',
    modelo: { rig: 'primate', alto: 1.05, pelo: '#a8481a', piel: '#4a3428', cara: '#6a4a3a', brazos: 1.25, mejillas: true, mechas: '#c0602a' } },
  { id: 'macaco', nombre: 'Macaco cangrejero', cientifico: 'Macaca fascicularis', cat: 'Mamíferos', grupo: 'herbivorous_mammal',
    dieta: 'Fruta, semillas, hojas, insectos, cangrejos', peso: '3–8 kg', donde: 'Sabah (muy común)', encaje: 'aprox',
    nota: 'Omnívoro; en el motor iría a herbívoro.', fuente: 'https://www.inaturalist.org/taxa/43459',
    modelo: { rig: 'primate', alto: 0.55, pelo: '#8a7a5e', piel: '#7a6656', cara: '#c9a48c', brazos: 0.85, cola: true } },
  { id: 'jabali-barbudo', nombre: 'Jabalí barbudo', cientifico: 'Sus barbatus', cat: 'Mamíferos', grupo: 'fungivorous_mammal',
    dieta: 'Fruta, raíces, setas, lombrices, carroña', peso: '41–150 kg', donde: 'Maliau y Sabah', encaje: 'aprox',
    nota: 'Come setas, pero es omnívoro y mucho más grande que el grupo (10 kg). No hay mamífero de Borneo que viva de setas a ese tamaño.', fuente: 'https://animaldiversity.org/accounts/Sus_barbatus/',
    modelo: { rig: 'cuadrupedo', largo: 1.1, alto: 0.62, ancho: 0.36, pelo: '#8c8070', barriga: '#a89c8c', lomo: '#5e5248', patas: '#4a4038', cola: 'cerdo', orejas: 'puntiagudas', hocico: 0.24, barba: '#e8e2d6', colmillos: true, cerdo: true } },
  { id: 'ardilla-prevost', nombre: 'Ardilla de Prevost', cientifico: 'Callosciurus prevostii', cat: 'Mamíferos', grupo: 'fungivorous_mammal',
    dieta: 'Fruta, semillas, insectos; las ardillas son las que más setas comen', peso: '0,25–0,5 kg', donde: 'Maliau y Sabah', encaje: 'aprox',
    nota: 'Variante pequeña del grupo: las ardillas son los mayores comedores de setas.', fuente: 'https://www.inaturalist.org/taxa/45955',
    modelo: { rig: 'cuadrupedo', largo: 0.32, alto: 0.2, ancho: 0.12, pelo: '#1c1a1a', barriga: '#b5532a', patas: '#1c1a1a', franja: '#f0eadc', cola: 'peluda', colaLargo: 0.36, orejas: 'redondas', hocico: 0.04 } },
  // ---- reptiles y anfibios
  { id: 'varano', nombre: 'Varano acuático', cientifico: 'Varanus salvator', cat: 'Reptiles', grupo: 'scavenging_mammal',
    dieta: 'Peces, ranas, roedores, aves, cangrejos y mucha carroña', peso: '~20 kg (hasta 50)', donde: 'Maliau', encaje: 'aprox',
    nota: 'El carroñero de 20 kg que hay de verdad en Borneo, pero es un reptil, no un mamífero.', fuente: 'https://en.wikipedia.org/wiki/Asian_water_monitor',
    modelo: { rig: 'reptil', largo: 1.9, ancho: 0.24, piel: '#3a3a2c', vientre: '#8a8a5e', puntos: '#c8b86a', cabezaLarga: true } },
  { id: 'dragon-bosque', nombre: 'Dragón del bosque de Borneo', cientifico: 'Gonocephalus bornensis', cat: 'Reptiles', grupo: 'herbivorous_lizard',
    dieta: 'Insectos (no come plantas)', peso: '~0,1 kg', donde: 'Maliau', encaje: 'sustituto',
    nota: 'En Borneo no hay lagartos herbívoros: es un sustituto para poder dibujar el grupo.', fuente: 'https://en.wikipedia.org/wiki/Gonocephalus_bornensis',
    modelo: { rig: 'reptil', largo: 0.42, ancho: 0.07, piel: '#4f8a3a', vientre: '#c4d48a', puntos: '#2c5a2a', cresta: '#2c5a2a' } },
  { id: 'eslizon-solar', nombre: 'Eslizón solar común', cientifico: 'Eutropis multifasciata', cat: 'Reptiles', grupo: 'thermophilic_lizard',
    dieta: 'Insectos (no come plantas)', peso: '~0,05 kg', donde: 'Maliau', encaje: 'sustituto',
    nota: 'Lagarto que toma el sol, como pide el grupo, pero come insectos: sustituto.', fuente: 'https://www.inaturalist.org/taxa/38008',
    modelo: { rig: 'reptil', largo: 0.32, ancho: 0.06, piel: '#7a5a34', vientre: '#d8c088', puntos: '#e0a040', brillo: true } },
  { id: 'vibora-verde', nombre: 'Víbora verde de Borneo', cientifico: 'Tropidolaemus subannulatus', cat: 'Reptiles', grupo: 'carnivorous_snake',
    dieta: 'Aves y roedores de los árboles, ranas', peso: '~0,2 kg (hasta 96 cm)', donde: 'Maliau (de lo más visto)', encaje: 'bueno',
    nota: '', fuente: 'https://www.ecologyasia.com/verts/snakes/bornean-keeled-pit-viper.htm',
    modelo: { rig: 'serpiente', largo: 0.95, grueso: 0.07, piel: '#3f9a3a', vientre: '#c8e07a', bandas: '#2a5a2a', cabezaAncha: true } },
  { id: 'piton-reticulada', nombre: 'Pitón reticulada', cientifico: 'Malayopython reticulatus', cat: 'Reptiles', grupo: 'carnivorous_snake',
    dieta: 'Mamíferos y aves', peso: 'muchos kg', donde: 'Maliau', encaje: 'aprox',
    nota: 'Variante grande del grupo de serpientes.', fuente: 'https://www.inaturalist.org/taxa/491869',
    modelo: { rig: 'serpiente', largo: 2.6, grueso: 0.15, piel: '#8a7a4a', vientre: '#d8cc9a', bandas: '#2c241a', rombos: '#c8b070' } },
  { id: 'rana-gigante-rio', nombre: 'Rana gigante de río', cientifico: 'Limnonectes leporinus', cat: 'Anfibios', grupo: 'frog',
    dieta: 'Insectos, cangrejos, otras ranas', peso: '~0,12 kg', donde: 'Maliau (endémica de Borneo)', encaje: 'bueno',
    nota: '', fuente: 'https://en.wikipedia.org/wiki/Giant_river_frog',
    modelo: { rig: 'rana', largo: 0.24, piel: '#6a5a3a', vientre: '#e8dcb4', puntos: '#3a3020' } },
  { id: 'rana-arboricola', nombre: 'Rana arborícola de orejas oscuras', cientifico: 'Polypedates macrotis', cat: 'Anfibios', grupo: 'frog',
    dieta: 'Insectos', peso: '~0,02 kg', donde: 'Maliau', encaje: 'aprox',
    nota: 'Variante pequeña del grupo.', fuente: 'https://www.inaturalist.org/taxa/26567',
    modelo: { rig: 'rana', largo: 0.14, piel: '#a87a4a', vientre: '#f0e0b8', puntos: '#4a2a1a', antifaz: '#2a1a12' } },
  // ---- aves
  { id: 'aguila-culebrera', nombre: 'Águila culebrera crestada', cientifico: 'Spilornis cheela', cat: 'Aves', grupo: 'carnivorous_bird',
    dieta: 'Serpientes, lagartos, ranas, mamíferos pequeños', peso: '0,4–1,8 kg', donde: 'Borneo', encaje: 'bueno',
    nota: '', fuente: 'https://peregrinefund.org/explore-raptors-species/eagles/crested-serpent-eagle',
    modelo: { rig: 'ave', largo: 0.62, plumas: '#4a3a2a', pecho: '#8a6a44', puntos: '#f0e6d2', pico: '#3a3a3a', cara: '#f2c63a', patas: '#f2c63a', cresta: true, alas: 1.3, rapaz: true } },
  { id: 'buho-pardo', nombre: 'Cárabo pardo', cientifico: 'Strix leptogrammica', cat: 'Aves', grupo: 'carnivorous_bird',
    dieta: 'Roedores, aves, insectos grandes', peso: '~0,8 kg', donde: 'Maliau', encaje: 'bueno',
    nota: 'Cazador nocturno del mismo grupo.', fuente: 'https://www.inaturalist.org/taxa/19922',
    modelo: { rig: 'ave', largo: 0.45, plumas: '#7a4a2a', pecho: '#d8b07a', puntos: '#4a2a14', pico: '#e8dcc4', cara: '#c48a52', patas: '#c8b8a0', buho: true, alas: 1.0 } },
  { id: 'calao', nombre: 'Cálao de cresta', cientifico: 'Anorrhinus galeritus', cat: 'Aves', grupo: 'herbivorous_bird',
    dieta: 'Sobre todo fruta (también cigarras, lagartos)', peso: '~1,2 kg', donde: 'Borneo', encaje: 'bueno',
    nota: '', fuente: 'https://en.wikipedia.org/wiki/Bushy-crested_hornbill',
    modelo: { rig: 'ave', largo: 0.7, plumas: '#3a2e28', pecho: '#5a4a40', pico: '#e8e0c8', cara: '#7ab8e0', patas: '#2a2a2a', calao: true, colaLarga: true, alas: 1.2 } },
  { id: 'gallo-bankiva', nombre: 'Gallo bankiva', cientifico: 'Gallus gallus', cat: 'Aves', grupo: 'herbivorous_bird',
    dieta: 'Semillas, brotes, insectos', peso: '0,5–1,4 kg', donde: 'Maliau', encaje: 'aprox',
    nota: 'Variante de suelo del grupo herbívoro.', fuente: 'https://www.inaturalist.org/taxa/882',
    modelo: { rig: 'ave', largo: 0.5, plumas: '#b8461e', pecho: '#2a2a2a', puntos: '#e8a03a', pico: '#d8c8a0', cara: '#d83a2a', patas: '#7a7a6a', gallo: true, alas: 0.8 } },
  { id: 'golondrina', nombre: 'Golondrina del Pacífico', cientifico: 'Hirundo javanica', cat: 'Aves', grupo: 'swallow',
    dieta: 'Insectos al vuelo', peso: '~0,013 kg', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://www.inaturalist.org/taxa/1578578',
    modelo: { rig: 'ave', largo: 0.16, plumas: '#22304a', pecho: '#e8e2da', cara: '#b8462a', pico: '#1a1a1a', patas: '#1a1a1a', horquilla: true, alas: 1.5 } },
  // ---- insectos y otros invertebrados
  { id: 'escarabajo-tigre', nombre: 'Escarabajo tigre dorado', cientifico: 'Cosmodela aurulenta', cat: 'Insectos', grupo: 'carnivorous_insect_iteroparous',
    dieta: 'Caza insectos, hormigas, arañas', peso: 'gramos', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://insect-books.com/cicindelidae/genus-cosmodela/',
    modelo: { rig: 'insecto', tipo: 'escarabajo', largo: 0.11, color: '#1f5aa8', brillo: '#3ad0c8', puntos: '#f2d24a', patasLargas: true, mandibulas: true } },
  { id: 'mantis-hoja-seca', nombre: 'Mantis hoja seca gigante', cientifico: 'Deroplatys desiccata', cat: 'Insectos', grupo: 'carnivorous_insect_semelparous',
    dieta: 'Caza insectos', peso: 'gramos', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://www.inaturalist.org/taxa/548630',
    modelo: { rig: 'insecto', tipo: 'mantis', largo: 0.2, color: '#8a6438', claro: '#b88e58', oscuro: '#4a321c' } },
  { id: 'libelula', nombre: 'Libélula parasol', cientifico: 'Neurothemis fluctuans', cat: 'Insectos', grupo: 'carnivorous_insect_semelparous',
    dieta: 'Caza insectos al vuelo (la ninfa, en el agua)', peso: 'gramos', donde: 'Maliau (las libélulas son lo más visto)', encaje: 'bueno',
    nota: 'Variante voladora del grupo.', fuente: 'https://www.inaturalist.org/taxa/107002',
    modelo: { rig: 'alado', tipo: 'libelula', largo: 0.16, color: '#b8241e', ala: '#c8402a', alaPunta: '#f0e0d0' } },
  { id: 'fulgorido', nombre: 'Fulgórido (mosca linterna)', cientifico: 'Pyrops whiteheadi', cat: 'Insectos', grupo: 'herbivorous_insect_iteroparous',
    dieta: 'Savia de los árboles', peso: 'gramos', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://bugoftheweek.com/blog/2024/1/8/lanternflies-vandals-in-vineyards-beauties-in-borneo',
    modelo: { rig: 'insecto', tipo: 'fulgorido', largo: 0.1, color: '#2a6a3a', claro: '#e8d24a', oscuro: '#c8321e', alas: true } },
  { id: 'escarabajo-atlas', nombre: 'Escarabajo atlas', cientifico: 'Chalcosoma atlas', cat: 'Insectos', grupo: 'herbivorous_insect_iteroparous',
    dieta: 'Savia y fruta (la larva, madera podrida)', peso: 'hasta 0,02 kg', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://www.inaturalist.org/taxa/334413',
    modelo: { rig: 'insecto', tipo: 'escarabajo', largo: 0.13, color: '#1a1e16', brillo: '#4a6a3a', cuernos: true } },
  { id: 'insecto-palo', nombre: 'Insecto palo gigante', cientifico: 'Phobaeticus kirbyi', cat: 'Insectos', grupo: 'herbivorous_insect_semelparous',
    dieta: 'Hojas', peso: 'gramos', donde: 'Maliau (Phobaeticus)', encaje: 'bueno',
    nota: 'De los insectos más largos del mundo.', fuente: 'https://en.wikipedia.org/wiki/Phobaeticus_kirbyi',
    modelo: { rig: 'insecto', tipo: 'palo', largo: 0.42, color: '#6a5a3a', claro: '#8a7a52' } },
  { id: 'cigarra', nombre: 'Cigarra gigante', cientifico: 'Megapomponia merula', cat: 'Insectos', grupo: 'herbivorous_insect_semelparous',
    dieta: 'Savia (la ninfa, de raíces bajo tierra)', peso: 'gramos', donde: 'Maliau', encaje: 'bueno',
    nota: '', fuente: 'https://www.inaturalist.org/taxa/541390',
    modelo: { rig: 'insecto', tipo: 'cigarra', largo: 0.09, color: '#3a3a2a', claro: '#8a9a5a', alas: true } },
  { id: 'oruga', nombre: 'Oruga de Rajah Brooke', cientifico: 'Trogonoptera brookiana (larva)', cat: 'Insectos', grupo: 'caterpillar',
    dieta: 'Hojas de Aristolochia', peso: 'gramos', donde: 'Borneo', encaje: 'bueno',
    nota: 'Se convierte en la mariposa de abajo.', fuente: 'https://en.wikipedia.org/wiki/Trogonoptera_brookiana',
    modelo: { rig: 'gusano', tipo: 'oruga', largo: 0.11, color: '#3a2a2a', puntos: '#d84a2a', segmentos: 9 } },
  { id: 'rajah-brooke', nombre: 'Mariposa alas de pájaro de Rajah Brooke', cientifico: 'Trogonoptera brookiana', cat: 'Insectos', grupo: 'butterfly',
    dieta: 'Néctar, sales minerales del suelo', peso: 'gramos', donde: 'Borneo', encaje: 'bueno',
    nota: '', fuente: 'https://en.wikipedia.org/wiki/Trogonoptera_brookiana',
    modelo: { rig: 'alado', tipo: 'mariposa', largo: 0.09, envergadura: 0.17, color: '#121212', ala: '#121212', alaPunta: '#2ae07a', cuello: '#d82a2a' } },
  { id: 'ninfa-arbol', nombre: 'Ninfa del árbol', cientifico: 'Idea stolli', cat: 'Insectos', grupo: 'butterfly',
    dieta: 'Néctar', peso: 'gramos', donde: 'Maliau', encaje: 'bueno',
    nota: 'Vuela despacio, como papel al viento.', fuente: 'https://www.inaturalist.org/taxa/196818',
    modelo: { rig: 'alado', tipo: 'mariposa', largo: 0.08, envergadura: 0.2, color: '#1a1a1a', ala: '#f2efe6', alaPunta: '#1a1a1a', manchado: true } },
  { id: 'lombriz', nombre: 'Lombriz de tierra', cientifico: 'Oligochaeta', cat: 'Insectos', grupo: 'earthworm',
    dieta: 'Hojarasca, hongos, bacterias del suelo', peso: 'gramos', donde: 'sin comprobar especie', encaje: 'aprox',
    nota: 'Genérica: no he comprobado la especie de Maliau.', fuente: '',
    modelo: { rig: 'gusano', tipo: 'lombriz', largo: 0.16, color: '#b86a5a', puntos: '#d88a7a', segmentos: 12 } },
  { id: 'pelotero', nombre: 'Escarabajo pelotero', cientifico: 'Scarabaeinae', cat: 'Insectos', grupo: 'dung_beetle',
    dieta: 'Excrementos', peso: 'gramos', donde: 'sin comprobar especie', encaje: 'aprox',
    nota: 'Genérico: no he comprobado la especie de Maliau.', fuente: '',
    modelo: { rig: 'insecto', tipo: 'escarabajo', largo: 0.07, color: '#1e2a1a', brillo: '#3a6a2a', bola: '#5a3e24' } },
  { id: 'termita', nombre: 'Termita en procesión', cientifico: 'Hospitalitermes', cat: 'Insectos', grupo: 'detritivorous_insect',
    dieta: 'Líquenes y restos de los troncos', peso: 'miligramos', donde: 'Maliau', encaje: 'bueno',
    nota: 'Salen de noche en columnas de miles.', fuente: 'https://link.springer.com/article/10.1007/s000400050047',
    modelo: { rig: 'insecto', tipo: 'termita', largo: 0.05, color: '#2a2018', claro: '#c8a07a' } },
];

export const PLANTAS = [
  { id: 'dipterocarpo', nombre: 'Seraya (dipterocarpo emergente)', cientifico: 'Shorea', cat: 'Árboles emergentes', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'El bosque bajo de Maliau es de dipterocarpos (74 especies), con emergentes de más de 30 m. Sus frutos tienen alas. Viven pegados a hongos (Amanita, Russula).',
    donde: 'Maliau', fuente: 'https://www.keybiodiversityareas.org/site/factsheet/16026', modelo: { tipo: 'dipterocarpo' } },
  { id: 'agathis', nombre: 'Kauri de Borneo', cientifico: 'Agathis borneensis', cat: 'Árboles emergentes', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'Domina el bosque de montaña baja de Maliau. Conífera de hoja ancha.',
    donde: 'Maliau', fuente: 'https://www.keybiodiversityareas.org/site/factsheet/16026', modelo: { tipo: 'agathis' } },
  { id: 'higuera', nombre: 'Higuera estranguladora', cientifico: 'Ficus', cat: 'Árboles del dosel', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'Especie clave: sus higos alimentan a orangutanes, cálaos y más de mil especies. Nace arriba y abraza al árbol con sus raíces.',
    donde: 'Maliau (Ficus punctata) y Borneo', fuente: 'https://www.etawau.com/Flora/Family__Moraceae/Genus_Ficus_ENG.htm', modelo: { tipo: 'higuera' } },
  { id: 'roble', nombre: 'Roble tropical', cientifico: 'Lithocarpus', cat: 'Árboles del dosel', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'Robles y laureles forman el bosque de montaña de Maliau.',
    donde: 'Maliau (Lithocarpus pulcher)', fuente: INAT, modelo: { tipo: 'roble' } },
  { id: 'dillenia', nombre: 'Simpoh gajah', cientifico: 'Dillenia excelsa', cat: 'Árboles del dosel', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'Hojas enormes y flores amarillas.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'dillenia' } },
  { id: 'pino-apio', nombre: 'Pino apio', cientifico: 'Phyllocladus hypophyllus', cat: 'Brezal de montaña (kerangas)', grupo: 'Arbusto (PFT)',
    nota: 'Conífera pequeña del brezal de montaña, sobre suelo pobre.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'pino-apio' } },
  { id: 'rododendro', nombre: 'Rododendro de flor larga', cientifico: 'Rhododendron longiflorum', cat: 'Brezal de montaña (kerangas)', grupo: 'Arbusto (PFT)',
    nota: 'Común en el brezal de Maliau, con flores rojas en tubo.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'rododendro' } },
  { id: 'palma-cola-pez', nombre: 'Palma cola de pez gigante', cientifico: 'Caryota no', cat: 'Palmas', grupo: 'Árbol (PFT de hoja ancha)',
    nota: 'Hojas partidas como colas de pez y racimos colgantes.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'palma-cola-pez' } },
  { id: 'pinanga', nombre: 'Palmita de sotobosque', cientifico: 'Pinanga veitchii', cat: 'Palmas', grupo: 'Arbusto (PFT)',
    nota: 'Palma pequeña de la sombra.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'pinanga' } },
  { id: 'jengibre-antorcha', nombre: 'Jengibre antorcha', cientifico: 'Etlingera elatior', cat: 'Sotobosque', grupo: 'Vegetación del subdosel',
    nota: 'Cañas altas de hojas y una flor roja como una antorcha que sale del suelo.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'jengibre' } },
  { id: 'phrynium', nombre: 'Phrynium', cientifico: 'Phrynium villosulum', cat: 'Sotobosque', grupo: 'Vegetación del subdosel',
    nota: 'Hojas grandes como palas en tallos largos.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'phrynium' } },
  { id: 'helecho-dipteris', nombre: 'Helecho de hoja ancha', cientifico: 'Dipteris conjugata', cat: 'Helechos', grupo: 'Vegetación del subdosel',
    nota: 'Hojas en abanico partidas en dos, en tallos altos.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'dipteris' } },
  { id: 'cuerno-alce', nombre: 'Helecho cuerno de alce', cientifico: 'Platycerium coronarium', cat: 'Helechos', grupo: 'Vegetación del subdosel',
    nota: 'Vive colgado de los troncos (epífito).', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'cuerno-alce' } },
  { id: 'rhaphidophora', nombre: 'Trepadora de hojas en teja', cientifico: 'Rhaphidophora korthalsii', cat: 'Trepadoras y epífitas', grupo: 'Vegetación del subdosel',
    nota: 'Sube por los troncos con las hojas pegadas como tejas.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'trepadora' } },
  { id: 'orquidea-tigre', nombre: 'Orquídea tigre', cientifico: 'Grammatophyllum speciosum', cat: 'Trepadoras y epífitas', grupo: 'Vegetación del subdosel',
    nota: 'La orquídea más grande del mundo; vive en las ramas.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'orquidea' } },
  { id: 'nepenthes-stenophylla', nombre: 'Planta jarra', cientifico: 'Nepenthes stenophylla', cat: 'Plantas carnívoras', grupo: 'Vegetación del subdosel',
    nota: 'La planta más observada en Maliau. Atrapa insectos en sus jarras.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'nepenthes' } },
  { id: 'nepenthes-rajah', nombre: 'Planta jarra gigante', cientifico: 'Nepenthes rajah', cat: 'Plantas carnívoras', grupo: 'Vegetación del subdosel',
    nota: 'Jarras enormes en el suelo. De Sabah.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'nepenthes-rajah' } },
  { id: 'tetrastigma', nombre: 'Liana de la rafflesia', cientifico: 'Tetrastigma diepenhorstii', cat: 'Trepadoras y epífitas', grupo: 'no está en el motor',
    nota: 'Liana leñosa de la familia de la vid que sube hasta la copa. La rafflesia vive dentro de ella y solo asoma la flor, junto a sus raíces.',
    donde: 'Borneo', fuente: 'https://www.inaturalist.org/taxa/Tetrastigma-diepenhorstii', modelo: { tipo: 'tetrastigma' } },
  { id: 'ratan', nombre: 'Ratán', cientifico: 'Calamus manan', cat: 'Trepadoras y epífitas', grupo: 'no está en el motor',
    nota: 'Palmera trepadora con espinas: sus tallos, largos y finos, suben hasta la copa enganchándose con látigos espinosos, y al pie forma una mata de hojas en pluma. De ella sale el mimbre de ratán.',
    donde: 'Borneo y Malasia', fuente: 'https://www.inaturalist.org/taxa/Calamus-manan', modelo: { tipo: 'ratan' } },
  { id: 'liana-colgante', nombre: 'Escalera de mono', cientifico: 'Phanera kockiana', cat: 'Trepadoras y epífitas', grupo: 'no está en el motor',
    nota: 'Liana de tallo aplanado y retorcido que cuelga de rama en rama, también sobre el río, en bucles que bajan casi hasta el suelo y con cortinas de tallos finos colgando. Los primates la usan para pasar de un árbol a otro.',
    donde: 'Borneo y Malasia', fuente: 'https://www.inaturalist.org/taxa/Phanera-kockiana', modelo: { tipo: 'liana-colgante' } },
  { id: 'enredadera', nombre: 'Pimienta trepadora', cientifico: 'Piper porphyrophyllum', cat: 'Trepadoras y epífitas', grupo: 'no está en el motor',
    nota: 'Enredadera de la familia de la pimienta que se pega a los troncos con raíces cortas y los cubre de hojas en corazón, oscuras y con los nervios claros.',
    donde: 'Borneo y Malasia', fuente: 'https://www.inaturalist.org/taxa/426429', modelo: { tipo: 'enredadera' } },
  { id: 'rafflesia', nombre: 'Rafflesia', cientifico: 'Rafflesia keithii', cat: 'Parásitas', grupo: 'no está en el motor',
    nota: 'La flor más grande del mundo; vive dentro de una liana y solo asoma la flor. En Maliau hay Rafflesia tengku-adlinii.',
    donde: 'Sabah y Maliau', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'rafflesia' } },
];

export const SETAS = [
  { id: 'amanita', nombre: 'Amanita esculpida', cientifico: 'Amanita sculpta', cat: 'Hongos de las raíces (ectomicorrizas)', grupo: 'Hongos ectomicorrícicos',
    nota: 'Vive pegada a las raíces de los dipterocarpos y les da nutrientes.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'amanita' } },
  { id: 'russula', nombre: 'Russula roja', cientifico: 'Russula', cat: 'Hongos de las raíces (ectomicorrizas)', grupo: 'Hongos ectomicorrícicos',
    nota: 'El género que más domina las raíces de los dipterocarpos.', donde: 'Borneo', fuente: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4401655/', modelo: { tipo: 'russula' } },
  { id: 'boleto-ruibarbo', nombre: 'Boleto ruibarbo', cientifico: 'Boletellus obscurecoccineus', cat: 'Hongos de las raíces (ectomicorrizas)', grupo: 'Hongos ectomicorrícicos',
    nota: 'Sombrero rojo y poros amarillos.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'boleto' } },
  { id: 'falo-velo', nombre: 'Falo de velo', cientifico: 'Phallus indusiatus', cat: 'Descomponedores (saprófitos)', grupo: 'Hongos saprófitos',
    nota: 'Una falda de encaje blanca; huele a podrido para atraer moscas.', donde: 'Maliau', fuente: INAT, modelo: { tipo: 'falo' } },
  { id: 'estrella-roja', nombre: 'Hongo estrella roja', cientifico: 'Aseroe rubra', cat: 'Descomponedores (saprófitos)', grupo: 'Hongos saprófitos',
    nota: 'La seta más observada de Sabah.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'estrella' } },
  { id: 'copa-tropical', nombre: 'Copa tropical peluda', cientifico: 'Cookeina tricholoma', cat: 'Descomponedores (saprófitos)', grupo: 'Hongos saprófitos',
    nota: 'Copitas naranjas con pelos sobre ramas caídas.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'copa' } },
  { id: 'repisa', nombre: 'Repisa de pie amarillo', cientifico: 'Microporus xanthopus', cat: 'Descomponedores (saprófitos)', grupo: 'Hongos saprófitos',
    nota: 'Embudos finos en troncos podridos.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'repisa' } },
  { id: 'poros-luminosos', nombre: 'Poros luminosos', cientifico: 'Favolaschia manipularis', cat: 'Setas que brillan', grupo: 'Hongos saprófitos',
    nota: 'Brilla de noche.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'luminosa', color: '#e8e0c0', luz: '#b8ff6a' } },
  { id: 'mycena-verde', nombre: 'Seta verde luminosa', cientifico: 'Mycena chlorophos', cat: 'Setas que brillan', grupo: 'Hongos saprófitos',
    nota: 'Brilla en verde de noche.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'luminosa', color: '#d8d0b8', luz: '#6aff9a', pequena: true } },
  { id: 'termitomyces', nombre: 'Seta de termitero', cientifico: 'Termitomyces', cat: 'Hongos con otros animales', grupo: 'Hongos saprófitos',
    nota: 'Las termitas la cultivan dentro del termitero y sale por arriba.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'termitomyces' } },
  { id: 'cordyceps', nombre: 'Hongo de las hormigas zombi', cientifico: 'Ophiocordyceps', cat: 'Hongos con otros animales', grupo: 'no está en el motor',
    nota: 'Infecta a una hormiga, la hace subir a una hoja y le sale un tallo de la cabeza.', donde: 'Sabah', fuente: 'https://www.inaturalist.org/places/13134', modelo: { tipo: 'cordyceps' } },
];
